### ISSUE TITLE
is this a stitch bug? incorrect alignment and merged contig

### ISSUE THREAD

**Issue by ShannonDaddy** [audy/stitch#4]
Hello, Audy.

my stitch command is:
python ./stitch-master/stitch/stitch.py -i test.1.fastq -j test.2.fastq -t 2 -s 90 -o test -p > test.align.txt

the content of input files is as follows.
### test.1.fastq

@M02915:12:000000000-AGBY0:1:1105:3779:9612 1:N:0:0
TTCAGCGGGTATCCCTACCTGATCCGAGGTCAACCTTTGATAAATTAGGGGTTGATGGCAAGCACACATCCAAACCTCCAAAGCGAAAGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTG
AGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAATACCAGGGGGTGCAATGTGCGTTCAAAGATTCGATGACTCACTCATAA
+
FFEFGGGFCFFGEGGGGFGAEDFAEFEGCFGGGGGGGGG,9FEE<FGEFGGGGGDGGFEAFFDFF8EFFGCFFGGGFGGEFDGGC:FGEGDGFAEC<FGCCGFFGGFGGDFC77FFGGGG:FFGCCEGFFFE@FGEGGGGGGGFGGGCDGFGGGEGGGFFGFGGGCFGG@CFGGF
<F7CB:88+BEGGGDGEEEEGGECGFGFFG67CEEG5E5*?FGFCECE5/:EGDGFGGFDD3BF:?FFF9FBAFAFFFFF:4A:B<)
### test.2.fastq

@M02915:12:000000000-AGBY0:1:1105:3779:9612 2:N:0:0
CACATTGCACCCCCTGGTATTCCGGGGGGTATGCCTGTTCGAGCGTCATTTCAACCCTCAAGCTCAGCTTGGTATTGGGTGTCGCCAGACAATGGTGCGCCTCAAAATTAGTGGCGGTGCCGTCTGGCTTCAAGCGTAGTAATTCCTTCGCTTTTGAGGTTTGGATGTGTTCTTGCCATCAACACCTCACTTACCAAATGTCGCCCTCCGCG
+
EGGGGG9@<FGEEGGGGGGG<E<<F:FC@FGGCFFGDFAEEFGGCFE=D,@=FDG8>AFFFCFFF<>F9@C9FCGGCCCFEC7FGFFGGGGC,?,?CGGEEGC79;<C?CCCE5=C5DF)9)**9))076B8F5057:4=*)**.).-2:??2.4((.12((())().(6>4).(6F0)3,)(-((.(44-),))(.--)(-(-(((-((
### test-contigs.fastq

@M02915:12:000000000-AGBY0:1:1105:3779:9612 1:N:0:0
TTCAGCGGGTATCCCTACCTGATCCGAGGTCAACCTTTGATAAATTAGGGGTTGATGGCAAGCACACATCCAAACCTCCAAAGCGAAAGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTGAGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAGTGAGGTGTTGATGGCAAGAACACATCCAAACCTCAAAAGCGAAGGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTGAGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAATACCAGGGGGTGCAATGTG
+M02915:12:000000000-AGBY0:1:1105:3779:9612 1:N:0:0
FFEFGGGFCFFGEGGGGFGAEDFAEFEGCFGGGGGGGGG,9FEEFGEFGGGGGFGGFEAFFDFF8EFFGCFFGGGFGGEFDGGC:FGEGDGFAEC<FGCCGFFGGFGGDFCFDFFGGGGCFFGCCEGFGFEGGGEGGGGGGGGGGGGFGFGGGEGGGFFGFGGGFFGGFFFGGFAF8GDF=@,DEGGGGGFEEEGGGFGFGGFGCFCFEGE4(.((-(),3)0F6(.)46(.)())(((21.((4.2??:2-.).**)*=4:7505F8B670))9**)9)FD5C=5ECCC?C<;97CGEEGGC?,?,CGGGGFF>GF7CEFCCCGGCF9C@9<F><FFFCFFFA>8GDF=@,D=EFCGGFEEAFDGFFCGGF@CF:F<<E<GGGGGGGEEGF<@9GGGGGE
### test.align.txt

> M02915:12:000000000-AGBY0:1:1105:3779:9612 1:N:0:0 (165.000)
> 1:TTCAGCGGGTATCCCTACCTGATCCGAGGTCAACCTTTGATAAATTAGGGGTTGATGGCAAGCACACATCCAAACCTCCAAAGCGAAAGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTGAGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAATACCAGGGGGTGCAATGTGCGTTCAAAGATTCGATGACTCACTCATAA--------------------
> 2:--------------------CGCGGAGGGCGACATTTGGTAAGTGAGGTGTTGATGGCAAGAACACATCCAAACCTCAAAAGCGAAGGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTGAGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAATACCAGGGGGTGCAATGTG
> C:TTCAGCGGGTATCCCTACCTGATCCGAGGTCAACCTTTGATAAATTAGGGGTTGATGGCAAGCACACATCCAAACCTCCAAAGCGAAAGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTGAGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAGTGAGGTGTTGATGGCAAGAACACATCCAAACCTCAAAAGCGAAGGAATTACTACGCTTGAAGCCAGACGGCACCGCCACTAATTTTGAGGCGCACCATTGTCTGGCGACACCCAATACCAAGCTGAGCTTGAGGGTTGAAATGACGCTCGAACAGGCATACCCCCCGGAATACCAGGGGGTGCAATGTG

The alignment is a little shifted, and the resulting contig should be shorter I assume. please check it for me, thanks a lot.

**Comment by audy** [comment]
I'm not maintaining Stitch anymore. Please use pandaseq.

**Comment by audy** [comment]
https://github.com/neufeld/pandaseq
